packages:
  - 'src'
  - 'scripts/localDeployer'
  # all packages in subdirs of components/
  - 'components/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/lib/**'
